"use client";

import { useEffect, useMemo, useState } from "react";

type Product = { name:string; type:string; objective:string[]; device:string; kpi:string; budget:string; lead:string; accent:string; desc:string; assets:string };
const products:Product[]=[
 {name:"Masthead",type:"High Impact",objective:["Maximum Awareness","Product Launch"],device:"Desktop + Mobile",kpi:"Reach · Viewability",budget:"Premium",lead:"7–10 days",accent:"blue",desc:"A dominant placement for moments that need immediate visibility across KLY properties.",assets:"Key visual, logo, headline, CTA, desktop & mobile adaptations"},
 {name:"Bottom Frame",type:"Display",objective:["Maximum Awareness","Traffic"],device:"Mobile",kpi:"Reach · CTR",budget:"Standard",lead:"5–7 days",accent:"red",desc:"A persistent mobile frame that keeps the brand visible during editorial consumption.",assets:"Mobile visual, logo, short copy, destination URL"},
 {name:"Headline",type:"Native Display",objective:["Traffic","Product Education"],device:"Desktop + Mobile",kpi:"CTR · Sessions",budget:"Standard",lead:"5–7 days",accent:"green",desc:"A native headline unit designed to earn attention in a familiar editorial reading flow.",assets:"Headline, thumbnail, brand label, destination URL"},
 {name:"Showcase",type:"Rich Display",objective:["Maximum Awareness","Product Launch"],device:"Desktop + Mobile",kpi:"Engagement · Viewability",budget:"Premium",lead:"7–10 days",accent:"orange",desc:"A visual storytelling canvas for launches, key features, or multiple products.",assets:"3–5 visuals, key messages, CTA, brand guide"},
 {name:"Native Ads",type:"Native",objective:["Product Education","Traffic"],device:"Desktop + Mobile",kpi:"CTR · Quality visits",budget:"Flexible",lead:"5–7 days",accent:"blue",desc:"Sponsored recommendations that align with the surrounding editorial experience.",assets:"Headline, image, brand name, URL"},
 {name:"Branded Article",type:"Content",objective:["Product Education","Product Launch"],device:"Desktop + Mobile",kpi:"Read time · Completion",budget:"Standard",lead:"10–14 days",accent:"green",desc:"Editorial-style storytelling developed with KLY to explain a product or brand point of view.",assets:"Brief, claims, brand assets, spokesperson access"},
 {name:"Video Ads",type:"Video",objective:["Maximum Awareness","Engagement"],device:"Desktop + Mobile",kpi:"VTR · Completion",budget:"Flexible",lead:"5–7 days",accent:"red",desc:"Video placements that bring sight, sound, and motion into premium KLY environments.",assets:"6–30s video, poster, tracking tags, CTA"},
 {name:"Microsite",type:"Experience",objective:["Product Education","Engagement"],device:"Desktop + Mobile",kpi:"Dwell time · Leads",budget:"Premium",lead:"14–21 days",accent:"orange",desc:"A dedicated branded destination for deeper stories, interactive content, and campaign utilities.",assets:"Content map, visuals, copy, brand guide, tracking plan"},
 {name:"Social Amplification",type:"Social",objective:["Engagement","Product Launch"],device:"Social Platforms",kpi:"Engagement · Views",budget:"Flexible",lead:"7–10 days",accent:"blue",desc:"Extend campaign stories through relevant KLY social channels and creator-led formats.",assets:"Social brief, key messages, assets, mandatory tags"},
 {name:"Lagi Diskon Widget",type:"Commerce",objective:["Promo Campaign","Traffic"],device:"Desktop + Mobile",kpi:"Clicks · Transactions",budget:"Performance",lead:"7–10 days",accent:"red",desc:"A commerce-led discovery widget connecting promotion content with shopping actions.",assets:"Product feed, prices, promo period, merchant links"}
];
const objectives=["All objectives","Maximum Awareness","Product Launch","Product Education","Traffic","Engagement","Promo Campaign"];

function ProductVisual({p,mobile=false}:{p:Product;mobile?:boolean}){return <div className={`product-visual ${p.accent} ${mobile?"mobile":""}`} aria-hidden="true"><div className="browser"><i/><i/><i/><b>KLY</b></div><div className="story"><strong/><span/><span/><span/></div><div className="placement"><small>Sponsored</small><b>{p.name}</b><span>See how your brand appears</span></div></div>}

export default function Home(){
 const [objective,setObjective]=useState("All objectives"),[type,setType]=useState("All types"),[query,setQuery]=useState("");
 const [detail,setDetail]=useState<Product|null>(null),[preview,setPreview]=useState<"Desktop"|"Mobile">("Desktop");
 const [compare,setCompare]=useState<string[]>([]),[compareOpen,setCompareOpen]=useState(false),[menu,setMenu]=useState(false),[sent,setSent]=useState(false),[generated,setGenerated]=useState(false);
 const [brief,setBrief]=useState({brand:"",industry:"Beauty",objective:"Product Launch",audience:"",budget:"Flexible",timeline:"Next 1–3 months"});
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==="Escape"){setDetail(null);setCompareOpen(false)}};addEventListener("keydown",close);return()=>removeEventListener("keydown",close)},[]);
 const types=["All types",...Array.from(new Set(products.map(p=>p.type)))];
 const filtered=useMemo(()=>products.filter(p=>(objective==="All objectives"||p.objective.includes(objective))&&(type==="All types"||p.type===type)&&`${p.name} ${p.type} ${p.desc}`.toLowerCase().includes(query.toLowerCase())),[objective,type,query]);
 const compared=products.filter(p=>compare.includes(p.name));
 const recommendations=useMemo(()=>products.filter(p=>p.objective.includes(brief.objective)).slice(0,3),[brief.objective]);
 const choose=(x:string)=>{setObjective(x);setTimeout(()=>document.getElementById("gallery")?.scrollIntoView({behavior:"smooth"}),10)};
 const toggle=(x:string)=>setCompare(v=>v.includes(x)?v.filter(n=>n!==x):v.length<3?[...v,x]:v);
 return <main>
  <header className="site-header"><a className="brand" href="#top" aria-label="KLY Ads Studio home"><img src="/kly-logo-web.png" alt="KLY — KapanLagi Youniverse"/><span>ADS STUDIO</span></a><button className="menu-button" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation">☰</button><nav className={menu?"open":""}><a href="#objectives">Solutions</a><a href="#use-cases">Use Cases</a><a href="#gallery">Ads Gallery</a><a href="#proof">Case Studies</a></nav><a className="button small" href="#contact">Build my campaign ↗</a></header>
  <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">KLY ADVERTISING DISCOVERY HUB</p><h1>From campaign brief to the right KLY solution—in minutes.</h1><p className="lede">Start with the business outcome, discover existing KLY products, and bring a clearer shortlist into the conversation with Sales.</p><div className="actions"><a className="button" href="#advisor">Get recommendations ↓</a><a className="text-link" href="#gallery">Explore all ad products →</a></div><div className="trust"><div><b>Existing inventory</b><span>no speculative formats</span></div><div><b>Objective-led</b><span>matched to the campaign job</span></div><div><b>Transparent</b><span>delivery considerations shown</span></div></div></div><aside className="advisor hero-example"><p className="eyebrow">LIVE EXAMPLE · BRIEF → SHORTLIST</p><h2>Beauty product launch</h2><small>Women 18–34 · 6 weeks · Product Launch</small><div className="example-list">{[["Masthead","Build reach","94%"],["Branded Article","Explain the story","88%"],["Social Amplification","Extend conversation","82%"]].map((x,i)=><button key={x[0]} onClick={()=>setDetail(products.find(p=>p.name===x[0])!)}><span>0{i+1}</span><span><b>{x[0]}</b><small>{x[1]}</small></span><strong>{x[2]}</strong></button>)}</div><small>Illustrative matching—not a media plan or performance forecast.</small></aside></section>
  <section className="section objectives" id="objectives"><SectionHead eyebrow="START WITH THE BUSINESS GOAL" title="Don’t browse formats. Solve a campaign job." copy="Each route recommends existing KLY products that make sense together—without inventing a new ad unit."/><div className="objective-grid">{objectives.slice(1).map((o,i)=><button key={o} onClick={()=>choose(o)}><span>0{i+1}</span><h3>{o}</h3><p>{["Own attention at scale across premium placements.","Turn a launch moment into reach, story, and action.","Help audiences understand before asking them to act.","Move qualified audiences to a destination.","Invite audiences to watch, explore, and participate.","Connect promotional discovery with measurable action."][i]}</p><b>View solution →</b></button>)}</div></section>
  <section className="section campaign-advisor" id="advisor"><SectionHead eyebrow="CAMPAIGN ADVISOR" title="Turn a simple brief into a focused shortlist." copy="Directional recommendations using existing KLY products. Final availability, targeting, pricing, and measurement stay with the Commercial team."/><div className="advisor-layout"><form className="brief-card" onSubmit={e=>{e.preventDefault();setGenerated(true)}}><div className="step-label"><span>01</span><div><b>Tell us about the campaign</b><small>Six fields. About one minute.</small></div></div><div className="brief-grid"><label>Brand / campaign<input value={brief.brand} onChange={e=>setBrief({...brief,brand:e.target.value})} placeholder="e.g. Lumière launch"/></label><label>Industry<select value={brief.industry} onChange={e=>setBrief({...brief,industry:e.target.value})}>{["Beauty","FMCG","Automotive","Finance","Technology","Property","Entertainment","Retail"].map(x=><option key={x}>{x}</option>)}</select></label><label>Primary objective<select value={brief.objective} onChange={e=>setBrief({...brief,objective:e.target.value})}>{objectives.slice(1).map(x=><option key={x}>{x}</option>)}</select></label><label>Target audience<input value={brief.audience} onChange={e=>setBrief({...brief,audience:e.target.value})} placeholder="e.g. Women 18–34, urban"/></label><label>Budget direction<select value={brief.budget} onChange={e=>setBrief({...brief,budget:e.target.value})}>{["To be discussed","Flexible","Standard","Premium"].map(x=><option key={x}>{x}</option>)}</select></label><label>Timeline<select value={brief.timeline} onChange={e=>setBrief({...brief,timeline:e.target.value})}>{["This month","Next 1–3 months","Still exploring"].map(x=><option key={x}>{x}</option>)}</select></label></div><button className="button">Generate recommended shortlist ↗</button><small>No data is transmitted or stored in this prototype.</small></form><div className={`recommendation-card ${generated?"ready":""}`}><div className="step-label"><span>02</span><div><b>Your recommended shortlist</b><small>{generated?`${brief.objective} · ${brief.industry}`:"Complete the brief to reveal three products"}</small></div></div>{generated?<>{recommendations.map((p,i)=><article className="recommendation-row" key={p.name}><span>0{i+1}</span><div><b>{p.name}</b><small>{p.desc}</small><em>{p.kpi} · {p.lead}</em></div><button onClick={()=>setDetail(p)}>↗</button></article>)}<div className="recommendation-actions"><button className="text-link" onClick={()=>setGenerated(false)}>Edit brief</button><button className="button small" onClick={()=>{setCompare(recommendations.map(p=>p.name));setCompareOpen(true)}}>Compare shortlist</button></div></>:<div className="recommendation-empty"><b>✦</b><h3>A useful recommendation starts with the campaign job.</h3><p>We’ll match your objective to three existing KLY products and explain the role of each.</p></div>}</div></div></section>
  <section className="section gallery" id="gallery"><SectionHead eyebrow="ADS GALLERY" title="Explore KLY’s existing ad products." copy="Filter by objective, understand the role of each product, and preview the experience before contacting sales."/><div className="filters"><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products or formats" aria-label="Search products"/></label><select value={objective} onChange={e=>setObjective(e.target.value)} aria-label="Objective filter">{objectives.map(x=><option key={x}>{x}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)} aria-label="Type filter">{types.map(x=><option key={x}>{x}</option>)}</select><button className="reset" onClick={()=>{setObjective("All objectives");setType("All types");setQuery("")}}>Reset</button></div><div className="results-line"><b>{filtered.length} products</b><span>{objective==="All objectives"?"Complete KLY product set":`Recommended for ${objective}`}</span></div>{filtered.length?<div className="product-grid">{filtered.map(p=><article className="product-card" key={p.name}><ProductVisual p={p}/><div className="card-body"><div className="tags"><span>{p.type}</span><span>{p.device}</span></div><h3>{p.name}</h3><p>{p.desc}</p><dl><Info a="Best for" b={p.objective[0]}/><Info a="Primary KPI" b={p.kpi}/><Info a="Lead time" b={p.lead}/></dl><div className="card-actions"><button className="button ghost" onClick={()=>setDetail(p)}>View experience</button><button className={`compare ${compare.includes(p.name)?"active":""}`} onClick={()=>toggle(p.name)}>{compare.includes(p.name)?"✓ Added":"＋ Compare"}</button></div></div></article>)}</div>:<div className="empty"><h3>No products match these filters.</h3><p>Try a broader objective or clear the search.</p><button className="button" onClick={()=>{setObjective("All objectives");setType("All types");setQuery("")}}>Reset filters</button></div>}</section>
  <section className="section use-cases" id="use-cases"><SectionHead eyebrow="USE-CASE RECIPES" title="See how products work together." copy="Starting configurations—not fixed bundles. Sales can adapt them to audience, timing, and budget."/><div className="recipe-grid">{[["Product launch","Create a launch moment, explain the story, then extend it.",["Masthead","Branded Article","Video Ads","Social Amplification"]],["Product education","Build understanding through editorial context and deeper exploration.",["Branded Article","Native Ads","Microsite"]],["Maximum awareness","Combine dominant visibility with repeatable reach.",["Masthead","Bottom Frame","Showcase","Video Ads"]],["Promo campaign","Connect offer discovery with traffic and commerce actions.",["Lagi Diskon Widget","Native Ads","Social Amplification"]]].map((r,i)=><article key={r[0] as string}><span>0{i+1}</span><h3>{r[0] as string}</h3><p>{r[1] as string}</p><div>{(r[2] as string[]).map(x=><button key={x} onClick={()=>setDetail(products.find(p=>p.name===x)!)}>{x} ↗</button>)}</div></article>)}</div></section>
  <section className="section proof" id="proof"><div><p className="eyebrow">FROM INVENTORY TO EVIDENCE</p><h2>A gallery should answer “why this product?”—not only show its shape.</h2><p>The homepage gives each product a role, KPI, delivery requirements, and a visual preview. Approved KLY results can be added later without changing the journey.</p><ul><li>Goal-based discovery</li><li>Desktop and mobile preview</li><li>Comparable product information</li><li>Shortlist carried into inquiry</li></ul></div><div className="proof-card"><label>DEMO CASE STUDY MODULE</label><h3>Lagi Diskon</h3><p>From promotion content to measurable commerce action.</p><div className="metric-row"><div><b>Reach</b><span>Insert approved data</span></div><div><b>Traffic</b><span>Insert approved data</span></div><div><b>Action</b><span>Insert approved data</span></div></div><small>Performance figures excluded pending commercial approval.</small></div></section>
  <section className="section blocker-section"><div><p className="eyebrow">BEYOND THE BANNER DEPENDENCY</p><h2>Not every solution depends on a display ad call.</h2><p>KLY can combine ad-served visibility with first-party content, branded experiences, commerce modules, and owned social distribution. This makes delivery dependencies clear without claiming immunity from every blocker.</p></div><div className="blocker-map"><article><span>AD-SERVED</span><b>Masthead · Bottom Frame · Showcase · Video</b><p>High visibility, with blocker exposure depending on the final serving method.</p></article><article><span>FIRST-PARTY / OWNED</span><b>Branded Article · Microsite · Lagi Diskon · Social</b><p>The core experience can remain available outside conventional banner inventory.</p></article></div></section>
  <section className="section how-section"><SectionHead eyebrow="HOW IT WORKS" title="From discovery to a sales-ready conversation." copy="The hub supports—not replaces—the Commercial team."/><div className="how-grid">{[["01","Define the job","Objective, audience, timing, and budget direction."],["02","Get a shortlist","See products matched to the campaign role."],["03","Preview and compare","Understand KPI, lead time, assets, and delivery."],["04","Validate with KLY","Sales confirms availability, targeting, pricing, and measurement."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
  <section className="section contact" id="contact"><div><p className="eyebrow">TURN DISCOVERY INTO A BETTER BRIEF</p><h2>Tell us the outcome. We’ll help shape the media solution.</h2><p>Your objective and shortlisted products travel with the inquiry, reducing back-and-forth with sales.</p></div>{sent?<div className="success"><b>✓</b><h3>Brief captured.</h3><p>This prototype simulates a successful inquiry. In production, it can route to the relevant KLY commercial team.</p><button className="text-link" onClick={()=>setSent(false)}>Create another brief →</button></div>:<form onSubmit={e=>{e.preventDefault();setSent(true)}}><div className="guided">I am a <select aria-label="Company type"><option>Brand</option><option>Agency</option></select> looking to <select value={objective==="All objectives"?"Maximum Awareness":objective} onChange={e=>setObjective(e.target.value)}>{objectives.slice(1).map(x=><option key={x}>{x}</option>)}</select> with a budget that is <select aria-label="Budget"><option>To be discussed</option><option>Flexible</option><option>Standard</option><option>Premium</option></select>.</div><div className="form-grid"><label>Name<input required placeholder="Your name"/></label><label>Company<input required placeholder="Company name"/></label><label>Work email<input required type="email" placeholder="name@company.com"/></label><label>Timeline<select><option>This month</option><option>Next 1–3 months</option><option>Still exploring</option></select></label></div><label>Selected products<div className="selected-products">{compare.length?compare.map(x=><span key={x}>{x}<button type="button" onClick={()=>toggle(x)}>×</button></span>):<em>No products selected yet—your brief can still be submitted.</em>}</div></label><button className="button">Request campaign recommendation ↗</button><small>Prototype only. No data is transmitted or stored.</small></form>}</section>
  <footer><a className="brand" href="#top" aria-label="KLY Ads Studio home"><img src="/kly-logo-web.png" alt="KLY — KapanLagi Youniverse"/><span>ADS STUDIO</span></a><p>Existing KLY ad products, made easier to discover and buy.</p><span>Homepage prototype · 2026</span></footer>
  {compare.length>0&&<div className="compare-bar"><div><b>{compare.length}/3 selected</b><span>{compare.join(" · ")}</span></div><button onClick={()=>setCompare([])}>Clear</button><button className="button small" onClick={()=>setCompareOpen(true)}>Compare products</button></div>}
  {detail&&<div className="modal-backdrop" role="dialog" aria-modal="true" aria-label={`${detail.name} details`} onMouseDown={e=>e.target===e.currentTarget&&setDetail(null)}><div className="modal"><button className="modal-close" onClick={()=>setDetail(null)} aria-label="Close">×</button><div className="modal-preview"><div className="toggle"><button className={preview==="Desktop"?"active":""} onClick={()=>setPreview("Desktop")}>Desktop</button><button className={preview==="Mobile"?"active":""} onClick={()=>setPreview("Mobile")}>Mobile</button></div><div className={preview==="Mobile"?"phone":"desktop-frame"}><ProductVisual p={detail} mobile={preview==="Mobile"}/></div><small>Illustrative placement preview—not final specification.</small></div><div className="modal-copy"><p className="eyebrow">{detail.type}</p><h2>{detail.name}</h2><p>{detail.desc}</p><dl><Info a="Best for" b={detail.objective.join(" · ")}/><Info a="Primary KPI" b={detail.kpi}/><Info a="Supported devices" b={detail.device}/><Info a="Creative assets" b={detail.assets}/><Info a="Indicative lead time" b={detail.lead}/><Info a="Budget band" b={detail.budget}/></dl><button className="button" onClick={()=>{toggle(detail.name);setDetail(null)}}>{compare.includes(detail.name)?"Remove from shortlist":"Add to shortlist"}</button></div></div></div>}
  {compareOpen&&<div className="modal-backdrop" role="dialog" aria-modal="true"><div className="compare-modal"><button className="modal-close" onClick={()=>setCompareOpen(false)} aria-label="Close">×</button><p className="eyebrow">SIDE-BY-SIDE</p><h2>Compare your shortlist.</h2><div className="compare-table"><div className="row heading"><span>Criteria</span>{compared.map(p=><b key={p.name}>{p.name}</b>)}</div>{[["Type","type"],["Best for","objective"],["Primary KPI","kpi"],["Device","device"],["Lead time","lead"],["Budget band","budget"]].map(([label,key])=><div className="row" key={key}><span>{label}</span>{compared.map(p=><div key={p.name}>{key==="objective"?p.objective.join(", "):String(p[key as keyof Product])}</div>)}</div>)}</div><div className="compare-footer"><button className="text-link" onClick={()=>setCompare([])}>Clear shortlist</button><a className="button" href="#contact" onClick={()=>setCompareOpen(false)}>Use in campaign brief →</a></div></div></div>}
 </main>
}
function SectionHead({eyebrow,title,copy}:{eyebrow:string;title:string;copy:string}){return <div className="section-head"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><p>{copy}</p></div>}
function Info({a,b}:{a:string;b:string}){return <div><dt>{a}</dt><dd>{b}</dd></div>}
